// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/matrix.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatrixService_ProcessRotatedMatrix_FullMethodName = "/matrix.MatrixService/ProcessRotatedMatrix"
)

// MatrixServiceClient is the client API for MatrixService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatrixServiceClient interface {
	ProcessRotatedMatrix(ctx context.Context, in *MatrixRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type matrixServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatrixServiceClient(cc grpc.ClientConnInterface) MatrixServiceClient {
	return &matrixServiceClient{cc}
}

func (c *matrixServiceClient) ProcessRotatedMatrix(ctx context.Context, in *MatrixRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, MatrixService_ProcessRotatedMatrix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatrixServiceServer is the server API for MatrixService service.
// All implementations must embed UnimplementedMatrixServiceServer
// for forward compatibility.
type MatrixServiceServer interface {
	ProcessRotatedMatrix(context.Context, *MatrixRequest) (*StatsResponse, error)
	mustEmbedUnimplementedMatrixServiceServer()
}

// UnimplementedMatrixServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatrixServiceServer struct{}

func (UnimplementedMatrixServiceServer) ProcessRotatedMatrix(context.Context, *MatrixRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessRotatedMatrix not implemented")
}
func (UnimplementedMatrixServiceServer) mustEmbedUnimplementedMatrixServiceServer() {}
func (UnimplementedMatrixServiceServer) testEmbeddedByValue()                       {}

// UnsafeMatrixServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatrixServiceServer will
// result in compilation errors.
type UnsafeMatrixServiceServer interface {
	mustEmbedUnimplementedMatrixServiceServer()
}

func RegisterMatrixServiceServer(s grpc.ServiceRegistrar, srv MatrixServiceServer) {
	// If the following call panics, it indicates UnimplementedMatrixServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatrixService_ServiceDesc, srv)
}

func _MatrixService_ProcessRotatedMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatrixServiceServer).ProcessRotatedMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatrixService_ProcessRotatedMatrix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatrixServiceServer).ProcessRotatedMatrix(ctx, req.(*MatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatrixService_ServiceDesc is the grpc.ServiceDesc for MatrixService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatrixService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matrix.MatrixService",
	HandlerType: (*MatrixServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessRotatedMatrix",
			Handler:    _MatrixService_ProcessRotatedMatrix_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/matrix.proto",
}
